// SPDX-License-Identifier: AGPL-3.0-or-later
// Generated by rules_requirements (rr_node_test); do not edit.
//
// Entry point of an rr_node_test: runs one node:test file in a child Node with
// two reporters — `spec` for the log, rr_node_reporter.mjs for the cases — and,
// once the child has exited, writes one JUnit <testcase> per test case to
// $XML_OUTPUT_FILE. It exits with the child's code: it never turns a failing
// test green or a passing one red. Failures that belong to no case (a load
// error, a non-zero exit after passing tests, a failing root hook) become
// target-scope error cases (property rr.scope=target).
"use strict";

const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { spawnSync } = require("node:child_process");

// Baked in by the rule (paths in the runfiles tree).
const TEST_REL = "{{TEST_REL}}"; // test file, relative to this file's directory
const TEST_RUNFILES = "{{TEST_RUNFILES}}"; // test file, relative to the runfiles root
const TEST_SHORT = "{{TEST_SHORT}}"; // test file, relative to the workspace (rr.file)
const REPORTER_REL = "{{REPORTER_REL}}"; // the rr reporter, relative to this file's directory
const VERIFIES_RUNFILES = "{{VERIFIES_RUNFILES}}"; // js/verifies.cjs, relative to the runfiles root
const TARGET = "{{TARGET}}"; // the test's label: names the suite
const LEVEL = "{{LEVEL}}"; // default level for cases that do not declare one
const ARGS = JSON.parse("{{ARGS}}"); // extra arguments for the test file

// `clocksync.test.js` -> `clocksync` (as rr_node_reporter.mjs's fileStem).
function fileStem(file) {
  const base = path.basename(file);
  return base.replace(/\.(test|spec)\.[cm]?[jt]s$/, "").replace(/\.[cm]?[jt]s$/, "");
}

function runfilesRoots() {
  return [process.env.RUNFILES_DIR, process.env.TEST_SRCDIR, process.env.JS_BINARY__RUNFILES].filter(Boolean);
}

// A runfile: next to this file first (the layout rules_js runs in), then under
// each runfiles root Bazel or rr_evidence may have set.
function locate(rel, runfilesPath) {
  const candidates = [];
  if (rel) candidates.push(path.resolve(__dirname, rel));
  if (runfilesPath) for (const root of runfilesRoots()) candidates.push(path.join(root, runfilesPath));
  return candidates.find((p) => fs.existsSync(p)) ?? candidates[0] ?? "";
}

// The workspace-relative form of a source path, for rr.file.
function workspacePath(file, test) {
  if (!file) return "";
  if (file === test) return TEST_SHORT;
  const norm = file.replace(/\\/g, "/");
  const m = /\/bazel-out\/[^/]+\/bin\/(.*)$/.exec(norm) || /\/[^/]+\.runfiles\/[^/]+\/(.*)$/.exec(norm);
  if (m) return m[1];
  const rel = path.relative(process.cwd(), file).replace(/\\/g, "/");
  return rel.startsWith("../") ? norm : rel;
}

// XML 1.0 cannot carry these; replaced like junit_writer.xml_safe (`#xNN`).
const INVALID_XML = /[\x00-\x08\x0b\x0c\x0e-\x1f\ud800-\udfff\ufffe\uffff]/gu;
const xmlSafe = (s) =>
  String(s ?? "").replace(INVALID_XML, (c) => "#x" + c.codePointAt(0).toString(16).toUpperCase().padStart(2, "0"));
const text = (s) => xmlSafe(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const attr = (s) =>
  text(s).replace(/"/g, "&quot;").replace(/\n/g, "&#10;").replace(/\r/g, "&#13;").replace(/\t/g, "&#09;");

// One-line summary of a failure for the `message` attribute.
function summary(message) {
  const lines = String(message ?? "")
    .split("\n")
    .map((l) => l.trim())
    .filter(Boolean);
  return lines.length ? lines[0] : "";
}

// One <testcase>; `c.props` is a list of [name, value] pairs.
function testcase(c) {
  const props = c.props.map(([k, v]) => `<property name="${attr(k)}" value="${attr(v)}"/>`).join("");
  const extra = (c.duration !== undefined ? ` time="${c.duration.toFixed(3)}"` : "") + (c.line ? ` line="${c.line}"` : "");
  let outcome = "";
  if (c.status === "failed") outcome = `<failure message="${attr(summary(c.message))}">${text(c.message)}</failure>`;
  else if (c.status === "error") outcome = `<error message="${attr(summary(c.message))}">${text(c.message)}</error>`;
  else if (c.status === "skipped") outcome = `<skipped message="${attr(c.message)}"/>`;
  return (
    `<testcase classname="${attr(c.classname)}" name="${attr(c.name)}"${extra}>` +
    (props ? `<properties>${props}</properties>` : "") +
    outcome +
    "</testcase>"
  );
}

function readRows(file) {
  let raw = "";
  try {
    raw = fs.readFileSync(file, "utf8");
  } catch {
    return [];
  }
  const rows = [];
  for (const line of raw.split("\n")) {
    if (!line) continue;
    try {
      rows.push(JSON.parse(line));
    } catch {
      // A line torn by a crash mid-write; the exit status still tells.
    }
  }
  return rows;
}

// The properties of a case from its rr diagnostics: requirement(s), level,
// artifact.* — then rr.file.
function caseProps(c, diags, test) {
  const ids = [];
  let level = "";
  const artifact = [];
  for (const [key, value] of diags) {
    if (key === "requirement") {
      for (const id of value.split(",").map((v) => v.trim())) if (id && !ids.includes(id)) ids.push(id);
    } else if (key === "level") level = value;
    else artifact.push([key, value]);
  }
  if (ids.length > 1) {
    process.stderr.write(
      `rr_node_test: warning: ${c.classname}::${c.name} names ${ids.join(", ")}; ` +
        "a test case verifies at most one requirement [RR-E101]\n",
    );
  }
  // One property per id: with several, ingest sees every one (and a later
  // rules_requirements quarantines the case) rather than a silent pick.
  const props = ids.map((id) => ["requirement", id]);
  if (level || LEVEL) props.push(["level", level || LEVEL]);
  return props.concat(artifact, [["rr.file", workspacePath(c.file, test)]]);
}

// Turns the reporter's rows and the exit status into <testcase> records, in
// the order node reported them.
function render(rows, run, test, plain) {
  const stem = fileStem(test);
  const diags = new Map();
  for (const row of rows) {
    if (row.kind !== "diag") continue;
    if (!diags.has(row.case)) diags.set(row.case, []);
    diags.get(row.case).push([row.key, row.value]);
  }
  const scoped = (classname, name, message, file, line) => ({
    classname,
    name,
    status: "error",
    message,
    line,
    props: [
      ["rr.scope", "target"],
      ["rr.file", workspacePath(file, test)],
    ],
  });
  const out = [];
  let cases = 0;
  let failed = false;
  let scopes = 0;
  for (const row of rows) {
    if (row.kind === "case") {
      cases++;
      failed = failed || row.status === "failed";
      out.push({ ...row, props: caseProps(row, diags.get(row.i) ?? [], test) });
    } else if (row.kind === "scope") {
      scopes++;
      out.push(scoped(row.classname, row.name, row.message, row.file, row.line));
    } else if (row.kind === "warning") {
      process.stderr.write(`rr_node_test: warning: ${row.message}\n`);
    }
  }
  const how = run.signal ? `was killed by ${run.signal}` : `exited ${run.code}`;
  const why = run.error ? `: ${run.error}` : "";
  if (plain) {
    // Node without --test-reporter (or RR_NODE_TEST_PLAIN=1): one result for
    // the whole file, as a plain js_test gives.
    out.push({
      classname: TARGET,
      name: TARGET.slice(TARGET.lastIndexOf(":") + 1) || stem,
      status: run.code === 0 ? "passed" : "failed",
      message: run.code === 0 ? "" : `node ${how}${why}; see test.log`,
      props: [["rr.synthetic", "true"]],
    });
  } else if (run.code !== 0 && cases === 0 && scopes === 0) {
    out.push(scoped(stem, "<load>", `node ${how} before reporting any test (a load error?)${why}; see test.log`, test));
  } else if (run.code !== 0 && scopes === 0 && !failed) {
    out.push(scoped(stem, "<exit-status>", `node ${how} although no test failed${why}; see test.log`, test));
  }
  return out;
}

function writeJUnit(file, cases) {
  const count = (status) => cases.filter((c) => c.status === status).length;
  const time = cases.reduce((t, c) => t + (c.duration || 0), 0);
  const xml =
    '<?xml version="1.0" encoding="UTF-8"?>\n<testsuites>\n' +
    `<testsuite name="${attr(TARGET)}" tests="${cases.length}" failures="${count("failed")}"` +
    ` errors="${count("error")}" skipped="${count("skipped")}" time="${time.toFixed(3)}">\n` +
    cases.map((c) => testcase(c) + "\n").join("") +
    "</testsuite>\n</testsuites>\n";
  // Never a half-written report: Bazel would read it as unparsable.
  fs.writeFileSync(file + ".tmp", xml);
  fs.renameSync(file + ".tmp", file);
}

function main() {
  const test = locate(TEST_REL, TEST_RUNFILES);
  const reporter = locate(REPORTER_REL, "");
  const verifies = VERIFIES_RUNFILES ? locate("", VERIFIES_RUNFILES) : "";
  const major = Number(process.versions.node.split(".")[0]);
  const plain = major < 20 || process.env.RR_NODE_TEST_PLAIN === "1";
  const xml = process.env.XML_OUTPUT_FILE;

  const scratch = fs.mkdtempSync(path.join(process.env.TEST_TMPDIR || os.tmpdir(), "rr_node_test-"));
  const casesOut = path.join(scratch, "cases.jsonl");
  const reporters = plain
    ? []
    : [
        "--test-reporter=spec",
        "--test-reporter-destination=stdout",
        `--test-reporter=${reporter}`,
        "--test-reporter-destination=stderr",
      ];
  // execArgv and NODE_OPTIONS (inherited) carry rules_js's node flags along.
  const child = spawnSync(process.execPath, [...process.execArgv, ...reporters, test, ...ARGS, ...process.argv.slice(2)], {
    stdio: "inherit",
    env: {
      ...process.env,
      RR_CASES_OUT: casesOut,
      RR_TEST_FILE: test,
      RR_TEST_STEM: fileStem(test),
      RR_TARGET: TARGET,
      ...(verifies ? { RR_NODE_VERIFIES: verifies } : {}),
    },
  });
  let code = child.status;
  if (code === null) {
    const signo = child.signal ? os.constants.signals[child.signal] : undefined;
    code = signo ? 128 + signo : 1;
  }
  const run = { code, signal: child.signal, error: child.error ? String(child.error.message || child.error) : "" };
  if (child.error) process.stderr.write(`rr_node_test: cannot run node: ${run.error}\n`);
  if (xml) writeJUnit(xml, render(readRows(casesOut), run, test, plain));
  fs.rmSync(scratch, { recursive: true, force: true });
  return code;
}

process.exitCode = main();
