package(default_visibility = ["//visibility:public"])

exports_files([
    "LICENSE",
    "docs/_static/logo/rules_requirements_logo.svg",
    "docs/_static/logo/rules_requirements_logo-dark.svg",
    "schema/rules_requirements.schema.json",
])

# `bazel run @rules_requirements -- validate requirements/`
alias(
    name = "rules_requirements",
    actual = "//python:rr",
)

alias(
    name = "rr",
    actual = "//python:rr",
)
