# SPDX-License-Identifier: AGPL-3.0-or-later
"""The verification-set lock (``verification.rrlock``).

A generated file (``rr sets lock --write``) that pins which cases each
entity's verification set holds, so a deleted, renamed or filtered test reads
as a missing member instead of silently shrinking a set::

    # Generated by `rr sets lock --write`; review its diff like a golden file.
    schema: rules_requirements/verification-lock/v1
    cases:
      //web:improv_provision_test:
        "improv_provision::provisionViaBle: survives a GATT flake via retry": PR-29
      //requirements:model_test:
        "[target]": PR-25

Each case maps to exactly one scalar id: a list value, a repeated key (the
model loader's duplicate-key check), one case under two spellings of its
target, or a case path that is not canonical (NFC, no surrounding blanks —
:func:`~rules_requirements.case_keys.case_path`) is ``lock-invalid``, so the
file cannot express two owners. The lock
never creates ownership — attribution only uses it for expected members.

The extension is deliberately not one :func:`~rules_requirements.model.model_files`
reads, so a lock next to the model never becomes part of it.
"""

from __future__ import annotations

import os
import unicodedata
from dataclasses import dataclass
from typing import Any, Mapping

from rules_requirements import labels
from rules_requirements._vendor import yaml

SCHEMA = "rules_requirements/verification-lock/v1"
_TOP_KEYS = ("schema", "cases")


class LockError(ValueError):
    """The lock cannot be read (rule ``lock-invalid``); ``problems`` lists every reason."""

    def __init__(self, problems: list[str]):
        self.problems = problems
        super().__init__("; ".join(problems))


@dataclass(frozen=True)
class LockEntry:
    target: str  # normalized
    path: str  # the case path ("[target]" for a synthetic result)
    owner: str
    line: int = 0  # line of the entry
    target_line: int = 0  # line of its target's key


@dataclass(frozen=True)
class Lock:
    entries: tuple[LockEntry, ...] = ()
    path: str = ""

    def owner_of(self, target: str, path: str) -> str | None:
        for e in self.entries:
            if e.target == target and e.path == path:
                return e.owner
        return None

    def of(self, entity: str) -> tuple[LockEntry, ...]:
        """The entries ``entity`` owns."""
        return tuple(e for e in self.entries if e.owner == entity)


def parse_lock(text: str, path: str = "", main_repo: str = "") -> Lock:
    """Parse a lock's text; raises :class:`LockError` listing every problem."""
    from rules_requirements.model import load_text

    where = path or "<lock>"
    try:
        docs = load_text(text)
    except yaml.YAMLError as exc:
        raise LockError([f"{where}: cannot load: {exc}"]) from None
    if len(docs) != 1 or not isinstance(docs[0], Mapping):
        raise LockError([f"{where}: a lock is one YAML mapping with 'schema' and 'cases'"])
    doc = docs[0]
    problems: list[str] = []
    for key in doc:
        if key not in _TOP_KEYS:
            problems.append(f"{where}: unknown key {key!r}")
    if doc.get("schema") != SCHEMA:
        problems.append(f"{where}: schema must be {SCHEMA!r}, got {doc.get('schema')!r}")
    cases = doc.get("cases")
    if cases is None:
        cases = {}
    if not isinstance(cases, Mapping):
        problems.append(f"{where}: 'cases' must map targets to {{case path: id}}")
        cases = {}
    entries: list[LockEntry] = []
    seen: dict[tuple[str, str], str] = {}
    key_lines: Mapping[Any, int] = getattr(cases, "key_lines", {})
    for target, members in cases.items():
        line: int = _line(key_lines, target) or getattr(members, "line", 0) or getattr(cases, "line", 0)
        at = f"{where}:{line}" if line else where
        if not isinstance(target, str):
            problems.append(f"{at}: target {target!r} is not a label")
            continue
        try:
            norm = labels.normalize_label(target, main_repo)
        except labels.BadTarget as exc:
            problems.append(f"{at}: {exc}")
            continue
        if not isinstance(members, Mapping):
            problems.append(f"{at}: {target}: must map case paths to one id each")
            continue
        case_lines: Mapping[Any, int] = getattr(members, "key_lines", {})
        for case, owner in members.items():
            entry_line = _line(case_lines, case) or line
            at = f"{where}:{entry_line}" if entry_line else where
            if not isinstance(case, str) or not case.strip():
                problems.append(f"{at}: {target}: case {case!r} is not a case path")
                continue
            canonical = unicodedata.normalize("NFC", case).strip()
            if case != canonical:
                # Case paths are NFC with no surrounding blanks; two spellings
                # of one path would be two entries for one case.
                problems.append(
                    f"{at}: {target}: case {case!r} is not a canonical case path (NFC, no surrounding "
                    f"blanks); write {canonical!r}"
                )
                continue
            if isinstance(owner, (list, tuple, Mapping)):
                problems.append(
                    f"{at}: {target}#{case} maps to {owner!r}; a case has exactly one owner (one id, not a list)"
                )
                continue
            if not isinstance(owner, str) or not owner.strip() or any(c in owner for c in ", \t"):
                problems.append(f"{at}: {target}#{case}: owner {owner!r} is not one id")
                continue
            key = (norm, case)
            if key in seen:
                problems.append(f"{at}: {norm}#{case} is locked twice (spelled {seen[key]!r} and {target!r})")
                continue
            seen[key] = target
            entries.append(LockEntry(norm, case, owner.strip(), entry_line, line))
    if problems:
        raise LockError(problems)
    return Lock(tuple(entries), path)


def _line(lines: Mapping[Any, int], key: Any) -> int:
    """The line ``key`` was written on, 0 if unknown (or unhashable)."""
    try:
        return lines.get(key, 0)
    except TypeError:
        return 0


def load_lock(path: str, main_repo: str = "", shown: str = "") -> Lock:
    """Read and parse the lock at ``path``; raises :class:`LockError`."""
    where = shown or path
    if not os.path.exists(path):
        raise LockError([f"{where}: the configured sets_lock does not exist (generate it with `rr sets lock --write`)"])
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError as exc:
        raise LockError([f"{where}: cannot read: {exc}"]) from None
    return parse_lock(text, where, main_repo)
