# SPDX-License-Identifier: AGPL-3.0-or-later
"""The verification-set lock (``verification.rrlock``).

A generated file (``rr sets lock --write``) that pins which cases each
entity's verification set holds, so a deleted, renamed or filtered test reads
as a missing member instead of silently shrinking a set::

    # Generated by `rr sets lock --write`; review its diff like a golden file.
    schema: rules_requirements/verification-lock/v1
    cases:
      //web:improv_provision_test:
        "improv_provision::provisionViaBle: survives a GATT flake via retry": PR-29
      //requirements:model_test:
        "[target]": PR-25

Each case maps to exactly one scalar id: a list value, a repeated key (the
model loader's duplicate-key check), one case under two spellings of its
target, or a case path that is not canonical (NFC, no surrounding blanks —
:func:`~rules_requirements.case_keys.case_path`) is ``lock-invalid``, so the
file cannot express two owners.

**The lock never creates ownership.** Which entity owns a case is decided by
:func:`rules_requirements.attribution.attribute` alone; a lock entry only adds
an *expected* member to its entity's verification set: ``missing`` when the
target ran without the case, ``not-run`` when the target did not run, and
``moved`` (with ``lock-owner-changed``) when the case now has another owner or
none. :func:`plan_lock` computes the lock ``rr sets lock`` writes from an
attribution; :func:`render_lock` is its deterministic text.

The extension is deliberately not one :func:`~rules_requirements.model.model_files`
reads, so a lock next to the model never becomes part of it.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
import unicodedata
from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any, Iterable, Mapping

from rules_requirements import labels
from rules_requirements._vendor import yaml
from rules_requirements.util import natural_key

if TYPE_CHECKING:  # pragma: no cover - typing only (attribution imports this module)
    from rules_requirements.attribution import Attribution
    from rules_requirements.model import Model

SCHEMA = "rules_requirements/verification-lock/v1"
HEADER = "# Generated by `rr sets lock --write`; review its diff like a golden file.\n"
SYNTHETIC_PATH = "[target]"  # == case_keys.SYNTHETIC_PATH
_TOP_KEYS = ("schema", "cases")


class LockError(ValueError):
    """The lock cannot be read (rule ``lock-invalid``); ``problems`` lists every reason."""

    def __init__(self, problems: list[str]):
        self.problems = problems
        super().__init__("; ".join(problems))


@dataclass(frozen=True)
class LockEntry:
    target: str  # normalized
    path: str  # the case path ("[target]" for a synthetic result)
    owner: str
    line: int = 0  # line of the entry
    target_line: int = 0  # line of its target's key

    @property
    def case(self) -> str:
        """``<target>#<path>``, the case key's string form."""
        return f"{self.target}#{self.path}"


@dataclass(frozen=True)
class Lock:
    """A parsed lock: one entry per locked case, each naming one owner."""

    entries: tuple[LockEntry, ...] = ()
    path: str = ""
    _index: Mapping[tuple[str, str], LockEntry] = field(default_factory=dict, init=False, repr=False, compare=False)

    def __post_init__(self) -> None:
        index: dict[tuple[str, str], LockEntry] = {}
        for entry in self.entries:
            if (entry.target, entry.path) in index:
                # parse_lock rejects this; a Lock built by hand must not hide
                # it behind a dict either: one case, one entry, one owner.
                raise LockError([f"{entry.case} is locked twice"])
            index[(entry.target, entry.path)] = entry
        object.__setattr__(self, "_index", index)

    def __len__(self) -> int:
        return len(self.entries)

    def entry(self, target: str, path: str) -> LockEntry | None:
        return self._index.get((target, path))

    def owner_of(self, target: str, path: str) -> str | None:
        """The one id ``target#path`` is locked to, or None."""
        entry = self._index.get((target, path))
        return entry.owner if entry is not None else None

    def of(self, entity: str) -> tuple[LockEntry, ...]:
        """The entries ``entity`` owns."""
        return tuple(e for e in self.entries if e.owner == entity)

    def targets(self) -> list[str]:
        return sorted({e.target for e in self.entries}, key=natural_key)


def parse_lock(text: str, path: str = "", main_repo: str = "") -> Lock:
    """Parse a lock's text; raises :class:`LockError` listing every problem."""
    from rules_requirements.model import load_text

    where = path or "<lock>"
    try:
        docs = load_text(text)
    except yaml.YAMLError as exc:
        raise LockError([f"{where}: cannot load: {exc}"]) from None
    if len(docs) != 1 or not isinstance(docs[0], Mapping):
        raise LockError([f"{where}: a lock is one YAML mapping with 'schema' and 'cases'"])
    doc = docs[0]
    problems: list[str] = []
    for key in doc:
        if key not in _TOP_KEYS:
            problems.append(f"{where}: unknown key {key!r}")
    if doc.get("schema") != SCHEMA:
        problems.append(f"{where}: schema must be {SCHEMA!r}, got {doc.get('schema')!r}")
    cases = doc.get("cases")
    if cases is None:
        cases = {}
    if not isinstance(cases, Mapping):
        problems.append(f"{where}: 'cases' must map targets to {{case path: id}}")
        cases = {}
    entries: list[LockEntry] = []
    seen: dict[tuple[str, str], str] = {}
    key_lines: Mapping[Any, int] = getattr(cases, "key_lines", {})
    for target, members in cases.items():
        line: int = _line(key_lines, target) or getattr(members, "line", 0) or getattr(cases, "line", 0)
        at = f"{where}:{line}" if line else where
        if not isinstance(target, str):
            problems.append(f"{at}: target {target!r} is not a label")
            continue
        try:
            norm = labels.normalize_label(target, main_repo)
        except labels.BadTarget as exc:
            problems.append(f"{at}: {exc}")
            continue
        if not isinstance(members, Mapping):
            problems.append(f"{at}: {target}: must map case paths to one id each")
            continue
        case_lines: Mapping[Any, int] = getattr(members, "key_lines", {})
        for case, owner in members.items():
            entry_line = _line(case_lines, case) or line
            at = f"{where}:{entry_line}" if entry_line else where
            if not isinstance(case, str) or not case.strip():
                problems.append(f"{at}: {target}: case {case!r} is not a case path")
                continue
            canonical = unicodedata.normalize("NFC", case).strip()
            if case != canonical:
                # Case paths are NFC with no surrounding blanks; two spellings
                # of one path would be two entries for one case.
                problems.append(
                    f"{at}: {target}: case {case!r} is not a canonical case path (NFC, no surrounding "
                    f"blanks); write {canonical!r}"
                )
                continue
            if isinstance(owner, (list, tuple, Mapping)):
                problems.append(
                    f"{at}: {target}#{case} maps to {owner!r}; a case has exactly one owner (one id, not a list)"
                )
                continue
            if not isinstance(owner, str) or not owner.strip() or any(c in owner for c in ", \t"):
                problems.append(f"{at}: {target}#{case}: owner {owner!r} is not one id")
                continue
            key = (norm, case)
            if key in seen:
                problems.append(f"{at}: {norm}#{case} is locked twice (spelled {seen[key]!r} and {target!r})")
                continue
            seen[key] = target
            entries.append(LockEntry(norm, case, owner.strip(), entry_line, line))
    if problems:
        raise LockError(problems)
    return Lock(tuple(entries), path)


def _line(lines: Mapping[Any, int], key: Any) -> int:
    """The line ``key`` was written on, 0 if unknown (or unhashable)."""
    try:
        return lines.get(key, 0)
    except TypeError:
        return 0


def load_lock(path: str, main_repo: str = "", shown: str = "") -> Lock:
    """Read and parse the lock at ``path``; raises :class:`LockError`."""
    where = shown or path
    if not os.path.exists(path):
        raise LockError([f"{where}: the configured sets_lock does not exist (generate it with `rr sets lock --write`)"])
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError as exc:
        raise LockError([f"{where}: cannot read: {exc}"]) from None
    return parse_lock(text, where, main_repo)


NO_LOCK = Lock(path="<no lock>")
"""Pass as ``lock=`` to :func:`~rules_requirements.trace.build_matrix` (or
:func:`~rules_requirements.attribution.attribute`) for "no lock", whatever
``config.sets_lock`` names (``rr report --no-lock``): the sets are not
pinned (an ``unpinned-sets`` gap), as without a configured lock. ``None``
reads the configured lock; an empty :class:`Lock` pins every set to nothing.
Compared by identity."""


def configured_lock(model: Model) -> Lock | None:
    """The lock ``config.sets_lock`` names (None without one); raises :class:`LockError`."""
    if not model.config.sets_lock:
        return None
    return load_lock(model.lock_path(), model.config.main_repo, shown=model.lock_path(shown=True))


# --------------------------------------------------------------------------- #
# Writing                                                                     #
# --------------------------------------------------------------------------- #

# Scalars written without quotes: a label without YAML indicators, and an id.
_PLAIN_LABEL = re.compile(r"^//[A-Za-z0-9_/.+-]*:[A-Za-z0-9_/.+=,~-]+$")
_PLAIN_ID = re.compile(r"^[A-Za-z][A-Za-z0-9_]*(?:[-.][A-Za-z0-9_]+)*$")
_YAML_WORDS = re.compile(r"^(?:y|n|yes|no|on|off|true|false|null)$", re.IGNORECASE)


# Characters a YAML stream may not carry raw (DEL, C1 controls, surrogates,
# U+FFFE/U+FFFF) or reads as a line break (NEL, U+2028, U+2029). JSON escapes
# the C0 controls itself; these are written as \uXXXX escapes, which a
# double-quoted YAML scalar reads back (anything else is kept as it is,
# readable).
_YAML_UNSAFE = re.compile("[\x7f-\x9f\u2028\u2029\ud800-\udfff\ufffe\uffff]")


def _quoted(text: str) -> str:
    """``text`` as a YAML double-quoted scalar that parses back to ``text``."""
    return _YAML_UNSAFE.sub(lambda m: f"\\u{ord(m.group(0)):04x}", json.dumps(text, ensure_ascii=False))


def _scalar(text: str, plain: re.Pattern[str]) -> str:
    if plain.match(text) and not _YAML_WORDS.match(text):
        return text
    return _quoted(text)  # a JSON string is a YAML double-quoted scalar


def render_lock(entries: Lock | Iterable[LockEntry]) -> str:
    """The lock file's text: deterministic (targets and paths in natural
    order), one ``"<path>": <id>`` line per case, every path quoted. Parsing
    it back gives the same entries."""
    items = entries.entries if isinstance(entries, Lock) else tuple(entries)
    by_target: dict[str, list[LockEntry]] = {}
    for entry in items:
        by_target.setdefault(entry.target, []).append(entry)
    out = [HEADER, f"schema: {SCHEMA}\n"]
    if not by_target:
        out.append("cases: {}\n")
        return "".join(out)
    out.append("cases:\n")
    for target in sorted(by_target, key=natural_key):
        out.append(f"  {_scalar(target, _PLAIN_LABEL)}:\n")
        for entry in sorted(by_target[target], key=lambda e: natural_key(e.path)):
            out.append(f"    {_quoted(entry.path)}: {_scalar(entry.owner, _PLAIN_ID)}\n")
    return "".join(out)


def write_lock(path: str, entries: Lock | Iterable[LockEntry]) -> None:
    """Write :func:`render_lock` to ``path`` atomically: a failed write never
    leaves half a lock behind."""
    text = render_lock(entries)
    fd, tmp = tempfile.mkstemp(prefix=".rrlock-", dir=os.path.dirname(os.path.abspath(path)))
    try:
        with os.fdopen(fd, "w", encoding="utf-8", newline="\n") as fh:
            fh.write(text)
        os.replace(tmp, path)
    except BaseException:
        try:
            os.remove(tmp)
        except OSError:
            pass
        raise


# --------------------------------------------------------------------------- #
# Computing the lock (`rr sets lock`)                                         #
# --------------------------------------------------------------------------- #


@dataclass(frozen=True)
class LockPlan:
    """What ``rr sets lock`` would write, and why it may not.

    ``lock`` keeps every entry ``removed`` lists unless removals were
    allowed, so a crashed or filtered run never shrinks a set silently.
    """

    lock: Lock
    added: tuple[LockEntry, ...] = ()
    removed: tuple[LockEntry, ...] = ()
    changed: tuple[tuple[LockEntry, LockEntry], ...] = ()  # (as locked, as attributed now)
    refused: tuple[str, ...] = ()  # quarantines: no lock is written over them
    allow_removals: bool = False

    @property
    def blocked(self) -> bool:
        """Writing must not happen: a quarantine, or removals that were not allowed."""
        return bool(self.refused) or (bool(self.removed) and not self.allow_removals)


def plan_lock(
    model: Model,
    attribution: Attribution,
    previous: Lock | None = None,
    *,
    allow_removals: bool = False,
) -> LockPlan:
    """The lock for ``attribution`` (computed over the evidence at hand).

    * A quarantine refuses the lock (``refused``): it has no owner to lock.
    * Every target present in the evidence is locked to exactly the owned
      keys observed. An owner change is listed in ``changed`` and allowed:
      the model change that caused it is reviewed in the same diff.
    * A target absent from the evidence keeps the entries that still match
      a claim of their locked owner (in hybrid mode also an entry whose owner
      claims nothing there and no other claim selects: it may be
      tag-owned), moves an entry exactly one other entity's claims now
      select to that entity (an owner change, in ``changed``), gains each
      literal selector's case, and ``[target]`` for a whole-target claim
      whose entity has no entry there yet.
    * Entries dropped from a target that ran, and stale entries of absent
      targets (no claim selects them), are ``removed``; they stay in
      ``lock``, unchanged, unless ``allow_removals``.

    The lock only records owners attribution already decided; it never
    decides one.
    """
    from rules_requirements import case_selectors

    refused = tuple(f"{q.code}: {q.detail}" for q in attribution.quarantined)
    prev = previous or Lock()
    ran = {t for t, run in attribution.targets.items() if run.ran}
    new: dict[tuple[str, str], LockEntry] = {}
    for key, owner in attribution.owner.items():
        if key.target in ran:
            new[(key.target, key.path)] = LockEntry(key.target, key.path, owner)
    claims = model.claims()
    hybrid = model.config.attribution != "model"
    removed: list[LockEntry] = []
    for entry in prev.entries:
        k = (entry.target, entry.path)
        if entry.target in ran:
            if k not in new:
                removed.append(entry)
            continue
        on_target = [c for c in claims if c.target == entry.target]
        own = [c for c in on_target if c.entity == entry.owner]
        if any(c.matches(entry.path) for c in own):
            new.setdefault(k, LockEntry(entry.target, entry.path, entry.owner))
            continue
        # The model moved the case: exactly one other entity's claims select
        # it now. An owner change, listed in `changed` and allowed (the model
        # change that caused it is reviewed in the same diff), not a removal.
        others = list(dict.fromkeys(c.entity for c in on_target if c.entity != entry.owner and c.matches(entry.path)))
        if len(others) == 1:
            new.setdefault(k, LockEntry(entry.target, entry.path, others[0]))
        elif hybrid and not own and not others:
            new.setdefault(k, LockEntry(entry.target, entry.path, entry.owner))  # may be tag-owned
        else:
            removed.append(entry)  # stale: no claim selects it (or several do: shared-case)
    for claim in claims:
        if claim.target in ran:
            continue
        if claim.pattern is None:
            if not any(e.target == claim.target and e.owner == claim.entity for e in new.values()):
                new.setdefault((claim.target, SYNTHETIC_PATH), LockEntry(claim.target, SYNTHETIC_PATH, claim.entity))
        elif claim.literal:
            try:
                path = case_selectors.literal_path(claim.pattern)
            except ValueError:  # BadSelector is a ValueError
                continue
            new.setdefault((claim.target, path), LockEntry(claim.target, path, claim.entity))
    # A removed entry whose case another entry took (a literal selector of
    # another entity) is an owner change, not a removal: `lock` keeps every
    # entry `removed` lists, unchanged, unless removals are allowed.
    removed = [e for e in removed if (e.target, e.path) not in new]
    if not allow_removals:
        for entry in removed:
            new[(entry.target, entry.path)] = LockEntry(entry.target, entry.path, entry.owner)
    added = [e for k, e in new.items() if prev.entry(*k) is None]
    changed = []
    for k, e in new.items():
        old = prev.entry(*k)
        if old is not None and old.owner != e.owner:
            changed.append((old, e))
    return LockPlan(
        lock=Lock(_sorted(new.values()), prev.path),
        added=_sorted(added),
        removed=_sorted(removed),
        changed=tuple(sorted(changed, key=lambda pair: _order(pair[1]))),
        refused=refused,
        allow_removals=allow_removals,
    )


def _order(entry: LockEntry) -> tuple[Any, ...]:
    return (natural_key(entry.target), natural_key(entry.path))


def _sorted(entries: Iterable[LockEntry]) -> tuple[LockEntry, ...]:
    return tuple(sorted(entries, key=_order))
