# SPDX-License-Identifier: AGPL-3.0-or-later
"""Migrating to one owner per test case: the attribution worksheet.

Today a test case counts toward *every* id it is tagged with and toward every
requirement whose ``verified_by`` names its target — the union. ``rr migrate
plan`` computes that union over a model and its evidence and lists every
evidence unit (one :class:`~rules_requirements.case_keys.CaseKey`) that counts
toward two or more entities, and every target named by two or more
requirements. The result is a worksheet (``.rrplan``, YAML) on which the
owners of those requirements record one decision per case:

* an entity id — the one requirement (user need, mitigation) it verifies;
* ``none`` — it verifies none of them;
* ``?`` — still open (the initial value).

Decisions are made per group (one test module/class of one target) and
overridden per case. ``rr migrate apply --stage tags`` then rewrites the
test sources to match (:mod:`rules_requirements.tag_codemod`);
:func:`model_edits` lists the ``verified_by`` edits the decisions imply.

Nothing here changes a verdict: the worksheet is data for people.
"""

from __future__ import annotations

import json
import os
import re
from dataclasses import dataclass, field
from typing import Any, Iterable, Mapping

from rules_requirements import config as cfg
from rules_requirements._vendor import yaml
from rules_requirements.case_keys import CaseKey, CaseRow, index_cases, run_targets
from rules_requirements.ingest import Evidence
from rules_requirements.model import Model
from rules_requirements.util import dedupe, natural_key

SCHEMA = "rules_requirements/attribution-worksheet/v1"
OPEN = "?"
NONE = "none"
NO_EVIDENCE = "no-evidence"  # a model_edits action

# Entities a tag counts toward today (trace.build_matrix); a tag naming a risk
# or test method is misdirected evidence and counts for nothing.
VERIFIABLE_KINDS = (cfg.REQUIREMENT, cfg.USER_NEED, cfg.MITIGATION)

HEADER = """\
# Attribution worksheet — generated by `rr migrate plan`.
#
# Every evidence unit below counts toward two or more entities today (each id
# it is tagged with, plus every requirement whose verified_by names its
# target). A test case verifies at most one requirement: decide its owner.
#
#   owner: PR-11   the one entity this case verifies
#   owner: none    it verifies none of them
#   owner: "?"     still open
#
# A group's owner applies to each of its cases; add `owner:` to a case to
# override it. `proposed` is a heuristic hint, never a decision. Re-running
# `rr migrate plan --merge THIS_FILE` keeps the decisions made so far.
"""


@dataclass
class Unit:
    """One evidence unit and what it counts toward under today's union."""

    row: CaseRow
    tags: tuple[str, ...]  # declared ids naming verifiable entities
    claims: tuple[str, ...]  # requirements whose verified_by names the target
    ignored: tuple[str, ...] = ()  # declared ids that count for nothing
    proposed: str = ""
    reason: str = ""

    @property
    def counts_toward(self) -> list[str]:
        return sorted(dedupe(list(self.tags) + list(self.claims)), key=natural_key)


@dataclass
class Plan:
    """The union-semantics census a worksheet is rendered from."""

    units: list[Unit]
    claimers: dict[str, list[str]]  # target -> requirements naming it in verified_by
    rows: dict[CaseKey, CaseRow] = field(default_factory=dict)

    @property
    def attributed(self) -> list[Unit]:
        return [u for u in self.units if u.counts_toward]

    @property
    def contested(self) -> list[Unit]:
        return [u for u in self.units if len(u.counts_toward) > 1 and not u.row.target_scope]


def verifiable_ids(model: Model) -> set[str]:
    return {eid for kind in VERIFIABLE_KINDS for eid in model.section(kind)}


def census(model: Model, evidence: Evidence) -> Plan:
    """What every evidence unit counts toward under today's semantics."""
    verifiable = verifiable_ids(model)
    claimers: dict[str, list[str]] = {}
    for req in sorted(model.requirements.values(), key=lambda r: natural_key(r.id)):
        for vb in req.verified_by:
            claimers.setdefault(vb.target, [])
            if req.id not in claimers[vb.target]:
                claimers[vb.target].append(req.id)
    rows = index_cases(evidence)
    units = []
    for row in rows.values():
        # A verified_by label matches the label the evidence was filed under,
        # exactly as trace.build_matrix matches it.
        labels = {c.target for c in row.cases if c.target}
        unit = Unit(
            row=row,
            tags=tuple(i for i in row.declared if i in verifiable),
            claims=tuple(dedupe([r for t in sorted(labels) for r in claimers.get(t, [])])),
            ignored=tuple(i for i in row.declared if i not in verifiable),
        )
        unit.proposed, unit.reason = _propose(model, unit)
        units.append(unit)
    return Plan(units=units, claimers=claimers, rows=rows)


def _ancestors(model: Model, req_id: str) -> set[str]:
    seen: set[str] = set()
    todo = [req_id]
    while todo:
        req = model.requirements.get(todo.pop())
        for parent in req.refines if req else ():
            if parent not in seen:
                seen.add(parent)
                todo.append(parent)
    return seen


def _propose(model: Model, unit: Unit) -> tuple[str, str]:
    """A single owner where the model or the evidence determines one, else ("", "")."""
    ids = unit.counts_toward
    if len(ids) < 2:
        return "", ""
    for cand in ids:
        others = [i for i in ids if i != cand]
        if set(others) <= _ancestors(model, cand):
            return cand, f"{cand} refines {', '.join(others)}, whose verdict rolls up from it"
    tagged = [t for t in unit.tags if t in ids]
    if len(tagged) == 1 and set(ids) - set(tagged) <= set(unit.claims):
        others = [i for i in ids if i != tagged[0]]
        return tagged[0], (
            f"the case's own tag is more specific than the whole-target verified_by of {', '.join(others)}"
        )
    return "", ""


# --------------------------------------------------------------------------- #
# The worksheet document                                                      #
# --------------------------------------------------------------------------- #


def _group_of(row: CaseRow) -> str:
    """The test module/class a case belongs to: the path up to ``::``."""
    if row.synthetic:
        return ""
    prefix, sep, _ = row.key.path.partition("::")
    return prefix if sep else ""


def worksheet(
    plan: Plan,
    *,
    inputs: Mapping[str, Iterable[str]] | None = None,
    previous: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    """The worksheet document (JSON-compatible) for ``plan``.

    ``previous`` (an earlier worksheet) carries its decisions over to the
    cases and groups that are still contested.
    """
    prev_cases = decisions(previous) if previous else {}
    prev_groups = {
        (g.get("target"), g.get("group")): g.get("owner")
        for g in (previous or {}).get("groups", []) or []
        if isinstance(g, dict)
    }
    by_group: dict[tuple[str, str], list[Unit]] = {}
    for unit in plan.contested:
        by_group.setdefault((unit.row.key.target, _group_of(unit.row)), []).append(unit)

    groups = []
    for (target, group), units in sorted(by_group.items(), key=lambda kv: (natural_key(kv[0][0]), kv[0][1])):
        owner = _owner(prev_groups.get((target, group)))
        proposals = {u.proposed for u in units}
        shared = proposals.pop() if len(proposals) == 1 else ""
        counts = sorted(dedupe([i for u in units for i in u.counts_toward]), key=natural_key)
        cases = []
        for u in units:
            entry: dict[str, Any] = {"path": u.row.key.path, "status": u.row.status}
            if u.counts_toward != counts:
                entry["counts_toward"] = u.counts_toward
            if u.ignored:
                entry["ignored_tags"] = list(u.ignored)
            if u.row.file:
                entry["file"] = u.row.file
            if u.proposed and not shared:
                entry["proposed"], entry["reason"] = u.proposed, u.reason
            decided = _owner(prev_cases.get(u.row.key))
            if decided != owner and decided != OPEN:
                entry["owner"] = decided
            cases.append(entry)
        g: dict[str, Any] = {"target": target, "group": group, "counts_toward": counts}
        tags = sorted(dedupe([i for u in units for i in u.tags]), key=natural_key)
        claims = sorted(dedupe([i for u in units for i in u.claims]), key=natural_key)
        if tags:
            g["tags"] = tags
        if claims:
            g["target_claims"] = claims
        if shared:
            g["proposed"], g["reason"] = shared, units[0].reason
        g["owner"] = owner
        g["cases"] = cases
        groups.append(g)

    involved = {g["target"] for g in groups}
    targets = []
    for target in sorted(plan.claimers, key=natural_key):
        owners = plan.claimers[target]
        if len(owners) < 2 and target not in involved:
            continue
        rows = [r for r in plan.rows.values() if r.key.target == target and not r.target_scope]
        keeps: dict[str, int] = {}
        for unit in plan.units:
            if unit.row.key.target == target and not unit.row.target_scope and len(unit.counts_toward) == 1:
                only = unit.counts_toward[0]
                if only in owners:
                    keeps[only] = keeps.get(only, 0) + 1
        t: dict[str, Any] = {
            "target": target,
            "claimed_by": list(owners),
            "shared": len(owners) > 1,
            "cases": len(rows),
            "per_case_output": any(not r.synthetic for r in rows),
        }
        if keeps:
            t["uncontested"] = keeps
        targets.append(t)

    target_scope = [
        {"case": str(u.row.key), "status": u.row.status, "counts_toward": u.counts_toward}
        for u in plan.units
        if u.row.target_scope and len(u.counts_toward) > 1
    ]
    doc: dict[str, Any] = {"schema": SCHEMA}
    if inputs:
        doc["inputs"] = {k: list(v) for k, v in inputs.items()}
    doc["summary"] = {}  # filled below, once the document it counts is complete
    doc["targets"] = targets
    doc["groups"] = groups
    if target_scope:
        doc["target_scope"] = target_scope
    doc["summary"] = summary(doc, units=len(plan.units), attributed=len(plan.attributed))
    return doc


def _owner(value: Any) -> str:
    text = "" if value is None else str(value).strip()
    if text.lower() == NONE:
        return NONE  # "None", "NONE": the keyword, whatever its case
    return text or OPEN


def summary(doc: Mapping[str, Any], **extra: int) -> dict[str, int]:
    decided = decisions(doc)
    out = dict(extra)
    out.update(
        {
            "contested_units": len(decided),
            "shared_targets": sum(1 for t in doc.get("targets", []) if t.get("shared")),
            "decided": sum(1 for v in decided.values() if v != OPEN),
            "open": sum(1 for v in decided.values() if v == OPEN),
        }
    )
    return out


def decisions(doc: Mapping[str, Any] | None) -> dict[CaseKey, str]:
    """Each contested case's effective decision: its own ``owner``, else its group's."""
    out: dict[CaseKey, str] = {}
    for g in (doc or {}).get("groups", []) or []:
        if not isinstance(g, dict):
            continue
        group_owner = _owner(g.get("owner"))
        for c in g.get("cases", []) or []:
            if isinstance(c, dict) and c.get("path") is not None:
                out[CaseKey(str(g.get("target", "")), str(c["path"]))] = _owner(c.get("owner", group_owner))
    return out


def owner_ids(owner: str) -> list[str]:
    """The ids a case decided ``owner`` must end up declaring: ``[owner]``, or none for ``none``."""
    return [] if owner == NONE else [owner]


def case_files(doc: Mapping[str, Any] | None) -> dict[CaseKey, str]:
    """Each contested case's test source (its row's ``file``), where the evidence named one."""
    out: dict[CaseKey, str] = {}
    for g in (doc or {}).get("groups", []) or []:
        if not isinstance(g, dict):
            continue
        for c in g.get("cases", []) or []:
            if isinstance(c, dict) and c.get("path") is not None and isinstance(c.get("file"), str) and c["file"]:
                out[CaseKey(str(g.get("target", "")), str(c["path"]))] = c["file"]
    return out


def model_edits(doc: Mapping[str, Any]) -> list[dict[str, str]]:
    """The ``verified_by`` edits the worksheet's decisions imply, per (target, requirement).

    ``action`` is ``remove`` (no case of the target is left for it), ``keep``
    (it still owns cases there, and no case went to anyone else),
    ``split`` (it keeps some cases while others went elsewhere — a whole-target
    reference cannot express that; it needs case selectors, from v0.3),
    ``open`` (undecided cases remain) or ``no-evidence`` (the evidence given
    has no result of the target, so nothing can be said: never a reason to
    remove the reference).
    """
    decided = decisions(doc)
    out = []
    for t in doc.get("targets", []) or []:
        if not isinstance(t, dict) or "target" not in t:
            continue
        target = t["target"]
        mine = {k: v for k, v in decided.items() if k.target == target}
        for req in t.get("claimed_by", []) or []:
            owns = bool((t.get("uncontested") or {}).get(req)) or any(v == req for v in mine.values())
            elsewhere = any(v not in (req, OPEN) for v in mine.values())
            pending = any(v == OPEN for v in mine.values())
            if not t.get("cases") and not mine:
                action, why = NO_EVIDENCE, f"the evidence given has no result of {target}; re-plan with its testlogs"
            elif pending:
                action, why = "open", "undecided cases remain"
            elif not owns:
                action, why = "remove", f"no case of {target} is left for {req}"
            elif elsewhere:
                action, why = "split", "it keeps some cases while others went elsewhere: needs case selectors (v0.3)"
            else:
                action, why = "keep", f"{req} owns every decided case"
            out.append({"target": target, "requirement": req, "action": action, "reason": why})
    return out


# --------------------------------------------------------------------------- #
# Verifying the result against test evidence                                  #
# --------------------------------------------------------------------------- #


@dataclass
class Offence:
    """One case the new evidence contradicts the worksheet on."""

    key: CaseKey
    reason: str
    expected: list[str]
    found: list[str] | None  # None: no result of the case in the new evidence

    def describe(self) -> str:
        found = "no result" if self.found is None else _ids(self.found)
        return f"{self.key}: {self.reason} (expected {_ids(self.expected)}, found {found})"


def _ids(ids: Iterable[str]) -> str:
    return "[" + ", ".join(ids) + "]"


@dataclass
class Verification:
    """The outcome of :func:`verify`."""

    offences: list[Offence] = field(default_factory=list)
    decided: int = 0  # decided cases found in the new evidence with exactly their owner
    # Cases with no result whose target has no result file in the new
    # evidence (a target CI does not run), tolerated with allow_missing.
    missing: list[CaseKey] = field(default_factory=list)
    # Decided cases declaring no id before or after: they count only through
    # verified_by. With a model, those that claims of exactly their owner
    # select; ``pending`` holds the others (case -> the entities claiming it).
    untagged: list[CaseKey] = field(default_factory=list)
    pending: list[tuple[CaseKey, list[str]]] = field(default_factory=list)
    # With a model: decided cases declaring exactly their owner that claims of
    # other entities select too (case -> those).
    also_claimed: list[tuple[CaseKey, list[str]]] = field(default_factory=list)
    unchanged: int = 0  # undecided cases whose ids match the baseline
    new: int = 0  # cases in the new evidence the baseline does not have

    @property
    def ok(self) -> bool:
        return not self.offences


def _is_label(target: str) -> bool:
    return target.startswith(("//", "@"))


def unkeyed(doc: Mapping[str, Any], evidence: Evidence) -> str:
    """Why ``evidence`` cannot be matched with the worksheet ``doc`` by
    target, else "": the worksheet's cases belong to build targets
    (``//pkg:name``) but the evidence files no case under any build target,
    only under ``suite:`` / ``record:`` pseudo-targets. A JUnit file's build
    target comes from its path (``bazel-testlogs/<pkg>/<name>/test.xml``, or
    a directory named ``testlogs``), so evidence copied into a directory of
    another name is keyed by suite name and no case matches."""
    wanted = sorted({k.target for k in decisions(doc) if _is_label(k.target)}, key=natural_key)
    found = run_targets(evidence)
    if not wanted or not found or any(_is_label(t) for t in found):
        return ""
    return (
        f"the worksheet's cases belong to build targets ({wanted[0]}"
        + (f" and {len(wanted) - 1} more" if len(wanted) > 1 else "")
        + "), but the evidence files every case under a pseudo-target ("
        + ", ".join(sorted(found, key=natural_key)[:3])
        + (", ..." if len(found) > 3 else "")
        + "): a test.xml's build target comes from its path, so keep the evidence under a directory named "
        "bazel-testlogs or testlogs (e.g. ci/bazel-testlogs/<pkg>/<name>/test.xml)"
    )


def _claimants(model: Model, evidence: Evidence) -> dict[CaseKey, list[str]]:
    """Each case of ``evidence`` (keyed as :func:`index_cases` files it) ->
    the entities whose claims select it, exactly as
    :func:`rules_requirements.attribution.attribute` selects them: a case
    selector reaches only the cases it matches, a whole claim every case of
    its target. Targets are compared normalized (``config.main_repo``)."""
    from rules_requirements.attribution import attribute
    from rules_requirements.case_keys import normalize_target

    att = attribute(model, evidence)
    main_repo = model.config.main_repo
    out: dict[CaseKey, list[str]] = {}
    for key in index_cases(evidence):
        selected = att.claimed_by.get(CaseKey(normalize_target(key.target, main_repo), key.path), ())
        out[key] = sorted(dedupe([c.entity for c in selected]), key=natural_key)
    return out


def verify(
    doc: Mapping[str, Any],
    evidence: Evidence,
    baseline: Evidence | None = None,
    *,
    allow_missing: bool = False,
    model: Model | None = None,
) -> Verification:
    """Check test evidence produced after ``rr migrate apply`` against the
    worksheet ``doc``.

    Every case the worksheet decides must declare exactly its owner in
    ``evidence`` (no id for ``none``). With a ``baseline`` (the evidence
    from before the rewrite), every other case must declare the same ids as
    before, and no case of the baseline may be missing from ``evidence``. A
    target-scope result (a whole run's exit status) carries the union of its
    cases' ids, which the decisions change: it must still be there, its ids
    are not compared.

    A case with no result is an offence, but with ``allow_missing`` one
    whose target has no result file at all in ``evidence`` (a HITL or
    manual target CI does not run) is only listed in ``missing``. A case
    missing from a target that did run stays an offence: it was renamed or
    lost. A target has run when the evidence has any result file for it
    (:func:`~rules_requirements.case_keys.run_targets`): a case, a
    synthetic whole-run result, or a report with no testcase at all (pytest
    collected nothing).

    Only declared ids are checked. A decided case that declared no id before
    the rewrite and declares none after counts only through ``verified_by``,
    which ``rr migrate apply`` cannot edit (it lists the edits): it is not an
    offence. With a ``model`` it is ``untagged`` when the entities whose
    claims select it (as :func:`~rules_requirements.attribution.attribute`
    selects: a case selector only the cases it matches, a whole claim every
    case of its target) are exactly its owner (none for ``none``), else
    ``pending`` a model edit (a target split between owners needs case
    selectors: ``rr migrate apply --stage model``); without one it is
    ``untagged``, its owner unchecked. "Before" is the baseline when it has
    the case, else the worksheet: a group that lists no ``tags`` has no
    tagged case. With a model, a decided case declaring exactly its owner
    that claims of other entities select is listed in ``also_claimed``: the
    claims decide its owner (``tag-mismatch``), or quarantine it when two
    entities claim it, so its tag alone does not make it its owner's.

    Cases are matched by :class:`~rules_requirements.case_keys.CaseKey`
    (:func:`~rules_requirements.case_keys.index_cases`), so the evidence of
    a Bazel ``py_test``, ``rr_node_test``, ``rr_case.h`` test or anything
    else rr ingests is checked alike.
    """
    out = Verification()
    decided = {k: v for k, v in decisions(doc).items() if v != OPEN}
    rows = index_cases(evidence)
    ran = run_targets(evidence)  # any result file for it, an empty one included
    before = index_cases(baseline) if baseline is not None else None
    claims = _claimants(model, evidence) if model is not None else {}
    untagged_groups = {
        CaseKey(str(g.get("target", "")), str(c["path"]))
        for g in doc.get("groups", []) or []
        if isinstance(g, dict) and not g.get("tags")
        for c in g.get("cases", []) or []
        if isinstance(c, dict) and c.get("path") is not None
    }

    def untagged_before(key: CaseKey) -> bool:
        if before is not None and key in before:
            return not before[key].declared
        return key in untagged_groups

    def absent(key: CaseKey, reason: str, expected: list[str]) -> None:
        if not allow_missing:
            out.offences.append(Offence(key, reason, expected, None))
        elif key.target not in ran:
            out.missing.append(key)  # its target did not run here
        else:
            out.offences.append(Offence(key, f"{reason}, though its target ran", expected, None))

    for key, owner in sorted(decided.items()):
        want = owner_ids(owner)
        row = rows.get(key)
        if row is None:
            if before is not None and key in before:
                continue  # reported below: a case of the baseline went missing
            absent(key, "a decided case has no result in the evidence", want)
            continue
        found = list(row.declared)
        if sorted(found) == want:
            out.decided += 1
            others = [r for r in claims.get(key, []) if r not in want]
            if others:
                out.also_claimed.append((key, others))
        elif not found and untagged_before(key):
            # Its owner is a verified_by edit, not a tag.
            if model is not None and claims.get(key, []) != want:
                out.pending.append((key, claims.get(key, [])))
            else:
                out.untagged.append(key)
        else:
            out.offences.append(Offence(key, "a decided case does not declare exactly its owner", want, found))
    if before is not None:
        for key, old in before.items():
            row = rows.get(key)
            expected = owner_ids(decided[key]) if key in decided else list(old.declared)
            if row is None:
                absent(key, "a case of the baseline has no result in the evidence", expected)
            elif key not in decided and not old.target_scope:
                if sorted(row.declared) != sorted(old.declared):
                    out.offences.append(Offence(key, "an undecided case's ids changed", expected, list(row.declared)))
                else:
                    out.unchanged += 1
        out.new = sum(1 for key in rows if key not in before)
    out.offences.sort(key=lambda o: (natural_key(o.key.target), natural_key(o.key.path)))
    out.missing.sort(key=lambda k: (natural_key(k.target), natural_key(k.path)))
    return out


# --------------------------------------------------------------------------- #
# Reading and writing                                                         #
# --------------------------------------------------------------------------- #


class _Flow(list):  # type: ignore[type-arg]
    """A list rendered inline (``[PR-11, PR-13]``)."""


class _Dumper(yaml.SafeDumper):  # type: ignore[misc]
    pass


_Dumper.add_representer(_Flow, lambda d, v: d.represent_sequence("tag:yaml.org,2002:seq", list(v), flow_style=True))


def _flow_lists(value: Any) -> Any:
    if isinstance(value, dict):
        return {k: _flow_lists(v) for k, v in value.items()}
    if isinstance(value, list):
        if all(isinstance(v, str) for v in value) and not any(k in v for v in value for k in ",[]{}#"):
            return _Flow(value)
        return [_flow_lists(v) for v in value]
    return value


def render_yaml(doc: Mapping[str, Any]) -> str:
    body = yaml.dump(
        _flow_lists(dict(doc)),
        Dumper=_Dumper,
        sort_keys=False,
        allow_unicode=True,
        default_flow_style=False,
        width=4096,
    )
    return HEADER + "\n" + str(body)


def render_json(doc: Mapping[str, Any]) -> str:
    return json.dumps(doc, indent=2, ensure_ascii=False) + "\n"


def _md(text: Any) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def _code(text: Any) -> str:
    s = _md(text)
    fence = "``" if "`" in s else "`"
    pad = " " if s.startswith("`") or s.endswith("`") else ""
    return f"{fence}{pad}{s}{pad}{fence}"


def render_markdown(doc: Mapping[str, Any]) -> str:
    s = doc.get("summary", {})
    out = ["# Attribution worksheet", ""]
    out.append(
        f"**{s.get('contested_units', 0)}** of {s.get('attributed', 0)} attributed evidence units count toward "
        f"two or more entities · **{s.get('shared_targets', 0)}** target(s) shared between requirements · "
        f"{s.get('decided', 0)} decided, {s.get('open', 0)} open"
    )
    out += ["", "A test case verifies at most one requirement. Decide each case's owner in the `.rrplan` file.", ""]

    def table(header: list[str], rows: list[list[str]]) -> None:
        out.append("| " + " | ".join(header) + " |")
        out.append("|" + "|".join("---" for _ in header) + "|")
        out.extend("| " + " | ".join(row) + " |" for row in rows)
        out.append("")

    if doc.get("targets"):
        out += ["## Targets named in verified_by", ""]
        table(
            ["Target", "Claimed by", "Cases", "Per-case output", "Uncontested cases"],
            [
                [
                    _code(t["target"]),
                    ", ".join(t["claimed_by"]) + (" (shared)" if t.get("shared") else ""),
                    str(t.get("cases", 0)),
                    "yes" if t.get("per_case_output") else "no — whole target only",
                    ", ".join(f"{k}: {v}" for k, v in sorted(t.get("uncontested", {}).items())) or "—",
                ]
                for t in doc["targets"]
            ],
        )
    if doc.get("groups"):
        out += ["## Contested evidence", ""]
        for g in doc["groups"]:
            title = f"{_code(g['target'])} — {_code(g['group'])}" if g.get("group") else _code(g["target"])
            out += [f"### {title}", ""]
            via = [f"tagged {', '.join(g['tags'])}"] if g.get("tags") else []
            via += [f"verified_by of {', '.join(g['target_claims'])}"] if g.get("target_claims") else []
            line = f"Counts toward **{', '.join(g['counts_toward'])}** ({'; '.join(via)})"
            line += f" · owner: **{_md(g.get('owner', OPEN))}**"
            if g.get("proposed"):
                line += f" · proposed: {g['proposed']} ({_md(g.get('reason', ''))})"
            out += [line, ""]
            table(
                ["Case", "Status", "Counts toward", "Proposed", "Owner"],
                [
                    [
                        _code(c["path"]),
                        c.get("status", ""),
                        ", ".join(c.get("counts_toward", [])) or "(group)",
                        c.get("proposed", "") or "—",
                        _md(c.get("owner", "(group)")),
                    ]
                    for c in g.get("cases", [])
                ],
            )
    missing = [e for e in model_edits(doc) if e["action"] == NO_EVIDENCE]
    if missing:
        out += [
            "## Targets without evidence",
            "",
            "**Warning:** the evidence given has no result of these targets, so nothing can be decided about "
            "them. Their `verified_by` references are not unused: re-run the plan with their test logs "
            "(a HITL or manual run, or a corrected `--evidence` path).",
            "",
        ]
        table(["Target", "Claimed by"], [[_code(e["target"]), e["requirement"]] for e in missing])
    edits = [e for e in model_edits(doc) if e["action"] not in ("open", NO_EVIDENCE)]
    if edits:
        out += ["## Model edits implied by the decisions", ""]
        table(
            ["Target", "Requirement", "Action", "Why"],
            [[_code(e["target"]), e["requirement"], e["action"], _md(e["reason"])] for e in edits],
        )
    if doc.get("target_scope"):
        out += [
            "## Target-scope results",
            "",
            "These describe how a whole target ended (exit status, load errors) and carry the union of its "
            "cases' ids today; from v0.3 they carry no ids. Nothing to decide.",
            "",
        ]
        table(
            ["Result", "Status", "Counts toward"],
            [[_code(r["case"]), r["status"], ", ".join(r["counts_toward"])] for r in doc["target_scope"]],
        )
    return "\n".join(out).rstrip() + "\n"


class WorksheetError(ValueError):
    pass


def load_worksheet(path: str) -> dict[str, Any]:
    """Read a ``.rrplan`` (YAML) or ``.json`` worksheet; raise :class:`WorksheetError`."""
    text = ""
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
        doc = json.loads(text) if path.endswith(".json") else yaml.safe_load(text)
    except (OSError, ValueError, yaml.YAMLError) as exc:
        hint = ""
        if isinstance(exc, yaml.YAMLError) and re.search(r"owner:\s*\?\s*(#|$)", text, re.MULTILINE):
            hint = " (an open owner is written with quotes: owner: '?')"
        raise WorksheetError(f"{path}: cannot read worksheet: {exc}{hint}") from exc
    if not isinstance(doc, dict) or doc.get("schema") != SCHEMA:
        raise WorksheetError(f"{path}: not an attribution worksheet (expected schema: {SCHEMA})")
    return doc


def check_worksheet(doc: Mapping[str, Any], model: Model | None = None) -> list[str]:
    """Problems with a (possibly hand-edited) worksheet; empty when usable.

    Each owner must be a string: ``?``, ``none`` (any case), or one of the
    entities the case counts toward today — a decision chooses among the
    existing claims, it never adds one. With a ``model``, the id must also be
    a requirement, user need or mitigation of it.
    """
    problems = []
    verifiable = verifiable_ids(model) if model is not None else None
    seen: set[CaseKey] = set()
    groups = doc.get("groups", [])
    if not isinstance(groups, list):
        return ["groups: expected a list"]
    for gi, g in enumerate(groups):
        where = f"groups[{gi}]"
        if not isinstance(g, dict) or not isinstance(g.get("target"), str) or not isinstance(g.get("cases"), list):
            problems.append(f"{where}: expected a mapping with target and cases")
            continue
        group_counts = _id_list(g.get("counts_toward"))
        group_owner = _owner(g.get("owner")) if _check_owner(f"{where}.owner", g, problems) else OPEN
        if not _check_id(
            f"{where}.owner", group_owner, group_counts, f"group {g.get('group', '')!r}", verifiable, problems
        ):
            group_owner = OPEN
        for ci, c in enumerate(g["cases"]):
            at = f"{where}.cases[{ci}]"
            if not isinstance(c, dict) or not isinstance(c.get("path"), str):
                problems.append(f"{at}: expected a mapping with a path")
                continue
            key = CaseKey(g["target"], c["path"])
            if key in seen:
                problems.append(f"{at}: {key} is listed twice")
            seen.add(key)
            counts = _id_list(c["counts_toward"]) if "counts_toward" in c else group_counts
            if "owner" in c:
                if _check_owner(f"{at}.owner", c, problems):
                    _check_id(f"{at}.owner", _owner(c["owner"]), counts, str(key), verifiable, problems)
            elif group_owner not in (OPEN, NONE) and counts is not None and group_owner not in counts:
                problems.append(
                    f"{at}: takes the group's owner {group_owner}, which {key} does not count toward "
                    f"({', '.join(counts)}); give it an owner of its own"
                )
    return problems


def _check_id(
    at: str, value: str, counts: list[str] | None, what: str, verifiable: set[str] | None, problems: list[str]
) -> bool:
    """Whether a decided id is one ``what`` counts toward (and, with a model, an entity of it)."""
    if value in (OPEN, NONE):
        return True
    if verifiable is not None and value not in verifiable:
        problems.append(f"{at}: {value} is not a requirement, user need or mitigation of the model")
        return False
    if counts is not None and value not in counts:
        problems.append(
            f"{at}: {value} is not among the ids {what} counts toward ({', '.join(counts) or 'none'}); "
            "an owner is one of those, or none"
        )
        return False
    return True


def _id_list(value: Any) -> list[str] | None:
    if not isinstance(value, list):
        return None
    return [str(v).strip() for v in value]


def _check_owner(at: str, holder: Mapping[str, Any], problems: list[str]) -> bool:
    """Whether ``holder``'s owner (if any) is a well-formed decision."""
    if "owner" not in holder:
        return True
    raw = holder["owner"]
    if isinstance(raw, (list, tuple)) or (isinstance(raw, str) and any(ch in raw.strip() for ch in ", \t")):
        problems.append(f"{at}: {raw!r} names more than one id; a test case verifies at most one")
        return False
    if raw is None or (isinstance(raw, str) and not raw.strip()):
        problems.append(f"{at}: empty; write '?' (quoted) to leave it open, or none")
        return False
    if not isinstance(raw, str):
        problems.append(f"{at}: {raw!r} is not an id; quote ids that YAML reads as numbers or booleans")
        return False
    return True


def plan_paths(paths: Iterable[str]) -> list[str]:
    """Input paths as recorded in the worksheet: relative to the current directory when below it."""
    here = os.getcwd()
    out = []
    for p in paths:
        ap = os.path.abspath(p)
        out.append(os.path.relpath(ap, here) if ap.startswith(here + os.sep) else p)
    return out


# --------------------------------------------------------------------------- #
# `rr migrate apply --stage model`: explicit selectors for every owner        #
# --------------------------------------------------------------------------- #

WHOLE_REASON = "migrated from tag ownership: the target reports no per-case results"


@dataclass
class ModelStage:
    """What ``rr migrate apply --stage model`` writes, and why it may not.

    ``additions`` maps each entity to ``{target: [selector, ...]}``: the
    selectors that make every case it owns through a tag (``attribution:
    hybrid``) a case it claims; ``whole`` the targets it owns only through
    their synthetic ``[target]`` result. ``data`` is each changed entity's
    new plain form (:func:`rules_requirements.edit.entity_to_dict`), and
    ``model`` the model with those entities, in ``attribution: model``, whose
    owner table :func:`check_model_stage` proved unchanged. ``refused`` lists
    why nothing may be written (a quarantine, a worksheet decision the
    evidence contradicts, a changed owner, a static claim error).

    ``unseen`` holds the worksheet's decided cases the evidence given does
    not hold (another lane's tests, say), with their decisions. Their owner
    comes from the worksheet: a case decided for an entity gets a literal
    selector of it (``from_worksheet`` lists those keys), and every unseen
    decided case must be selected, statically, by exactly its decided owner
    (by no claim when decided ``none``), or the stage is refused.
    """

    additions: dict[str, dict[str, list[str]]] = field(default_factory=dict)
    whole: dict[str, list[str]] = field(default_factory=dict)
    data: dict[str, dict[str, Any]] = field(default_factory=dict)
    model: Model | None = None
    owners: int = 0
    refused: list[str] = field(default_factory=list)
    unseen: dict[str, str] = field(default_factory=dict)  # decided case key -> decision, not in the evidence
    from_worksheet: list[str] = field(default_factory=list)  # unseen keys given a literal selector


def _decided_against(doc: Mapping[str, Any] | None, owner: Mapping[CaseKey, str], cases: Iterable[CaseKey],
                     main_repo: str) -> tuple[list[str], dict[CaseKey, str]]:  # fmt: skip
    """Worksheet decisions the attribution disagrees with, and the decided
    cases it does not hold (with their decisions)."""
    from rules_requirements.case_keys import normalize_target

    present = set(cases)
    wrong: list[str] = []
    unseen: dict[CaseKey, str] = {}
    for key, decision in decisions(doc).items():
        if decision == OPEN:
            continue
        norm = CaseKey(normalize_target(key.target, main_repo), key.path)
        if norm not in present:
            unseen[norm] = decision
            continue
        got = owner.get(norm)
        if (decision == NONE and got is not None) or (decision != NONE and got != decision):
            wrong.append(
                f"{norm}: the worksheet decided {decision}, the evidence makes it "
                f"{'owned by ' + got if got else 'owned by nobody'} (apply --stage tags and re-run the tests first)"
            )
    return wrong, unseen


def _compress(
    paths: list[str],
    target_keys: list[CaseKey],
    owned_by_ent: set[CaseKey],
    skipped: set[CaseKey],
    others: list[Any],
    own: list[Any],
) -> list[str]:
    """Selectors for ``paths`` (one entity, one target): a ``*`` glob where it
    selects exactly cases the entity owns, none of them skipped, overlaps no
    other entity's claim and none of its own; literals for the rest."""
    from rules_requirements import case_selectors as cs

    wanted = set(paths)

    def safe(glob: str) -> bool:
        hit = [k for k in target_keys if cs.matches(glob, k.path)]
        if len([k for k in hit if k.path in wanted]) < 2:
            return False
        if any(k not in owned_by_ent or k in skipped for k in hit):
            return False
        return not any(c.pattern is None or cs.witness(glob, c.pattern) is not None for c in others + own)

    out: list[str] = []
    left = list(paths)
    if safe("*") and all(k in owned_by_ent for k in target_keys):
        covered = {k.path for k in target_keys if cs.matches("*", k.path)}
        out.append("*")
        left = [p for p in left if p not in covered]
    groups: dict[str, list[str]] = {}
    for path in left:
        prefix, sep, _ = path.rpartition("::")
        if sep:
            groups.setdefault(prefix + "::", []).append(path)
    for prefix, members in sorted(groups.items()):
        glob = cs.escape(prefix) + "*"
        if len(members) > 1 and safe(glob):
            out.append(glob)
            left = [p for p in left if not cs.matches(glob, p)]
    out.extend(cs.escape(p) for p in sorted(left, key=natural_key))
    return out


def model_stage(
    model: Model,
    evidence: Evidence,
    doc: Mapping[str, Any] | None = None,
    *,
    compress: bool = False,
) -> ModelStage:
    """Explicit selectors for every current owner (``rr migrate apply --stage model``).

    The owners are decided by :func:`rules_requirements.attribution.attribute`
    over ``evidence``; nothing here assigns one. Every case owned through a
    tag gets a selector of its owner (a literal per case, or with
    ``compress`` a ``*`` glob where that is exact), then
    :func:`check_model_stage` proves the owner table unchanged under
    ``attribution: model`` and the claims statically disjoint.

    A case the worksheet decided but ``evidence`` does not hold keeps the
    worksheet's owner: a literal selector of the decided entity (unless one
    of its claims selects it already), and a refusal unless exactly that
    entity's claims select it (none for ``none``). Nothing is lost silently.
    """
    from rules_requirements import case_selectors as cs
    from rules_requirements import edit
    from rules_requirements.attribution import attribute

    stage = ModelStage()
    before = attribute(model, evidence)
    stage.owners = len(before.owner)
    for q in before.quarantined:
        stage.refused.append(f"{q.code}: {q.detail}")
    wrong, unseen = _decided_against(doc, before.owner, before.cases, model.config.main_repo)
    stage.unseen = {str(k): v for k, v in sorted(unseen.items(), key=lambda kv: _key_order(kv[0]))}
    stage.refused.extend(wrong)
    if stage.refused:
        return stage

    tagged: dict[str, dict[str, list[str]]] = {}
    for key, via in before.via.items():
        if via == "tag":
            tagged.setdefault(before.owner[key], {}).setdefault(key.target, []).append(key.path)
    claims = model.claims()
    for ent_id in sorted(tagged, key=natural_key):
        for target in sorted(tagged[ent_id], key=natural_key):
            paths = sorted(tagged[ent_id][target], key=natural_key)
            if paths == ["[target]"]:
                stage.whole.setdefault(ent_id, []).append(target)
                continue
            paths = [p for p in paths if p != "[target]"]
            keys = [k for k in before.cases if k.target == target and not before.cases[k].synthetic]
            if compress:
                # A glob must not reach a decided case of another owner the
                # evidence lacks: count those cases too.
                far = [k for k in unseen if k.target == target and k.path != cs.SYNTHETIC_PATH]
                selectors = _compress(
                    paths,
                    keys + far,
                    {k for k in keys if before.owner.get(k) == ent_id} | {k for k in far if unseen[k] == ent_id},
                    {k for k in keys if before.cases[k].status == "skipped"},
                    [c for c in claims if c.target == target and c.entity != ent_id],
                    [c for c in claims if c.target == target and c.entity == ent_id],
                )
            else:
                selectors = [cs.escape(p) for p in paths]
            stage.additions.setdefault(ent_id, {})[target] = selectors
    # Decided on the worksheet, absent from this evidence: the worksheet's owner.
    for key, decision in sorted(unseen.items(), key=lambda kv: _key_order(kv[0])):
        if decision == NONE or key.path == cs.SYNTHETIC_PATH:
            continue
        if any(c.entity == decision and c.target == key.target and c.matches(key.path) for c in claims):
            continue  # one of its claims selects it already
        if any(cs.matches(g, key.path) for g in stage.additions.get(decision, {}).get(key.target, [])):
            continue  # so does a selector just added (a compressed glob)
        stage.additions.setdefault(decision, {}).setdefault(key.target, []).append(cs.escape(key.path))
        stage.from_worksheet.append(str(key))

    new_model = model
    for ent_id in sorted(set(stage.additions) | set(stage.whole), key=natural_key):
        ent = model.get(ent_id)
        if ent is None:  # pragma: no cover - an owner is always an entity of the model
            continue
        data = edit.entity_to_dict(ent)
        rel = CLAIM_RELATION.get(ent.kind, "verified_by")
        items = list(data.get(rel, []))
        for target, selectors in stage.additions.get(ent_id, {}).items():
            for item in items:
                if (
                    isinstance(item, dict)
                    and item.get("cases")
                    and not item.get("whole")
                    and _same_target(item.get("target"), target, model.config.main_repo)
                    and set(item) <= {"target", "cases"}
                ):
                    item["cases"] = list(item["cases"]) + selectors
                    break
            else:
                items.append({"target": target, "cases": selectors})
        for target in stage.whole.get(ent_id, []):
            items.append({"target": target, "whole": True, "reason": WHOLE_REASON})
        data[rel] = items
        stage.data[ent_id] = data
        built, problems = edit.dict_to_entity(ent.kind, data, ent.location)
        if built is None or problems:
            stage.refused.append(f"{ent_id}: the new claims do not read back: {'; '.join(problems)}")
            return stage
        new_model = new_model.with_entity(built)
    stage.model = new_model
    stage.refused.extend(check_model_stage(model, new_model, evidence))
    after_claims = new_model.claims()
    for key, decision in sorted(unseen.items(), key=lambda kv: _key_order(kv[0])):
        who = sorted({c.entity for c in after_claims if c.target == key.target and c.matches(key.path)},
                     key=natural_key)  # fmt: skip
        if who != ([] if decision == NONE else [decision]):
            stage.refused.append(
                f"{key}: the worksheet decided {decision} (not in the evidence given), but the new claims select it "
                f"for {', '.join(who) or 'nobody'}"
            )
    return stage


def _key_order(key: CaseKey) -> tuple[Any, Any]:
    return (natural_key(key.target), natural_key(key.path))


CLAIM_RELATION = {cfg.USER_NEED: "validated_by", cfg.REQUIREMENT: "verified_by", cfg.MITIGATION: "verified_by"}


def _same_target(label: Any, target: str, main_repo: str) -> bool:
    from rules_requirements.labels import try_normalize

    return isinstance(label, str) and try_normalize(label, main_repo) == target


def check_model_stage(before: Model, after: Model, evidence: Evidence) -> list[str]:
    """Why ``after`` may not replace ``before``: an owner that changed (the
    model-mode attribution of ``after`` must give every case the owner the
    attribution of ``before`` gave it, through a claim), a quarantine, or a
    static claim error (``check_claims``: shared-case, same-code, a bad
    selector or target)."""
    from dataclasses import replace

    from rules_requirements.attribution import attribute
    from rules_requirements.validate import validate

    problems = []
    old = attribute(before, evidence)
    model_mode = replace(after, config=replace(after.config, attribution="model"))
    new = attribute(model_mode, evidence)
    # Under attribution: model a tag owns nothing (it is an unclaimed-tag
    # issue), so an unchanged owner is one owned through a claim.
    for key in sorted(set(old.owner) | set(new.owner), key=_key_order):
        if old.owner.get(key) != new.owner.get(key):
            problems.append(f"owner of {key} would change: {old.owner.get(key)} -> {new.owner.get(key)}")
    problems.extend(f"{q.code}: {q.detail}" for q in new.quarantined)
    hard = ("shared-case", "same-code-multiple-owners", "bad-selector", "bad-target")
    old_errors = {(i.code, i.message) for i in validate(before) if i.severity == "error"}
    for issue in validate(model_mode):
        if issue.severity == "error" and issue.code in hard and (issue.code, issue.message) not in old_errors:
            problems.append(f"check_claims: {issue}")
    return problems
