"""Rule implementations behind //rr:defs.bzl."""

RrModelInfo = provider(
    doc = "Requirements model files.",
    fields = {
        "srcs": "depset of model files",
        "lock": "the verification-set lock (`File`), or None",
    },
)

RrReportInfo = provider(
    doc = "A traceability report built by rr_report.",
    fields = {
        "json": "the JSON report (`File`), or None",
        "lane": "the lane it was built for (\"\" for none)",
        "on_attribution_error": "\"fail\" or \"warn\"",
        "lock": "the verification-set lock it read (`File`), or None",
    },
)

RrEvidenceInfo = provider(
    doc = "Test evidence produced by rr_evidence.",
    fields = {"testlogs": "tree artifact laid out like bazel-testlogs"},
)

def _rr_model_impl(ctx):
    files = depset(ctx.files.srcs)
    lock = ctx.file.lock

    # The lock is no model file: it rides in the runfiles, never in `files`
    # (which other rules pass to `rr` as the model).
    runfiles = ctx.runfiles(files = ctx.files.srcs + ([lock] if lock else []))
    return [
        DefaultInfo(files = files, runfiles = runfiles),
        RrModelInfo(srcs = files, lock = lock),
    ]

rr_model_rule = rule(
    implementation = _rr_model_impl,
    doc = "Groups requirements model files (see rr_model).",
    attrs = {
        "srcs": attr.label_list(allow_files = [".yaml", ".yml", ".json"], mandatory = True),
        "lock": attr.label(allow_single_file = [".rrlock"], doc = "The verification-set lock (`rr sets lock`)."),
    },
)

# A baked argument standing for the runfiles path of `executable`. Not
# `$(rootpath <target>)`: that expands a target's files to build, which for a
# py_binary under Bazel 7 are its launcher and its .py source (an error).
EXECUTABLE_ARG = "$(rr_executable)"

def _executable_path(ctx):
    """The runfiles path `EXECUTABLE_ARG` stands for.

    An executable target (a py_binary, a cc_test) gives its executable: under
    Bazel 7 a py_binary's files are its launcher *and* its .py source. Anything
    else (a checked-in script, a genrule output, a filegroup) must be exactly
    one file, as `$(rootpath)` required in 0.1.0.
    """
    ftr = ctx.attr.executable[DefaultInfo].files_to_run
    if ftr and ftr.executable:
        return ftr.executable.short_path
    files = ctx.files.executable
    if len(files) != 1:
        fail("%s: `executable` %s must be one file or an executable target, got %d file(s)" % (
            ctx.label,
            ctx.attr.executable.label,
            len(files),
        ))
    return files[0].short_path

def _rr_main_impl(ctx):
    args = []
    for a in ctx.attr.baked_args:
        if a == EXECUTABLE_ARG:
            if not ctx.attr.executable:
                fail("%s in baked_args needs `executable`" % EXECUTABLE_ARG)
            args.append(_executable_path(ctx))
            continue
        expanded = ctx.expand_location(a, ctx.attr.data)
        if "$(rootpaths " in a or "$(locations " in a:
            args.extend([p for p in expanded.split(" ") if p])
        else:
            args.append(expanded)
    ctx.actions.write(
        output = ctx.outputs.out,
        content = """# Generated by rules_requirements (rr_main); do not edit.
import sys

from rules_requirements.bazel import run_generated_main

if __name__ == "__main__":
    sys.exit(run_generated_main({entry}, {args}))
""".format(entry = json.encode(ctx.attr.entry), args = json.encode(args)),
    )

rr_main = rule(
    implementation = _rr_main_impl,
    doc = "Writes a Python main with its arguments baked in (see run_generated_main).",
    attrs = {
        "entry": attr.string(mandatory = True, values = ["cli", "pytest", "wrap", "bazel"]),
        "baked_args": attr.string_list(),
        "data": attr.label_list(allow_files = True),
        # Not `executable = True`: rr_wrapped_test's `test` may be a checked-in
        # script or a genrule output, as `$(rootpath test)` allowed in 0.1.0.
        "executable": attr.label(allow_files = True, cfg = "target"),
        "out": attr.output(mandatory = True),
    },
)

def _workspace_of(label):
    return label.workspace_name or "_main"

def _rr_evidence_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name + "/testlogs")
    args = ctx.actions.args()
    args.add("run-tests")
    args.add("--out", out.path)
    args.add("--timeout", str(ctx.attr.timeout))
    tools = []
    for t in ctx.attr.tests:
        ftr = t[DefaultInfo].files_to_run
        if not ftr or not ftr.executable:
            fail("%s is not executable" % t.label)
        tools.append(ftr)
        args.add("--test", "%s=%s=%s" % (t.label, ftr.executable.path, _workspace_of(t.label)))
        if RunEnvironmentInfo in t:
            # The test's own `env` attribute (as `bazel test` would set it).
            for k, v in t[RunEnvironmentInfo].environment.items():
                args.add("--env", "%s=%s=%s" % (t.label, k, v))
    ctx.actions.run(
        executable = ctx.executable._tool,
        arguments = [args],
        outputs = [out],
        tools = tools,
        mnemonic = "RrEvidence",
        progress_message = "Running %d test(s) for evidence %%{label}" % len(ctx.attr.tests),
        execution_requirements = {"no-remote-exec": "1"} if ctx.attr.local else {},
    )
    return [
        DefaultInfo(files = depset([out])),
        RrEvidenceInfo(testlogs = out),
    ]

_rr_evidence = rule(
    implementation = _rr_evidence_impl,
    doc = """Runs tests inside a build action and collects their JUnit.

The output is a directory laid out like `bazel-testlogs`, so `rr_report` maps
each file back to its test label. Failing tests do not fail the build — they
are evidence, and the report shows them as FAILED. Use this for hermetic,
cacheable reports (and golden tests of them); for suites that cannot run in a
sandbox (hardware-in-the-loop), aggregate real `bazel-testlogs` with the `rr`
CLI instead.""",
    attrs = {
        # Exec configuration: the binaries must run on the execution platform.
        # (The target configuration would reuse `bazel test`'s binaries, but
        # with test-configuration trimming — Bazel 7's default — a non-test
        # rule depending on tests collides with the tests' own actions.) The
        # cost is a second build of the tests; for large or hardware suites,
        # aggregate the real bazel-testlogs with `rr report` instead.
        "tests": attr.label_list(cfg = "exec", mandatory = True, doc = "Test targets to run."),
        "timeout": attr.int(default = 300, doc = "Per-test timeout in seconds."),
        "local": attr.bool(default = False, doc = "Never execute remotely."),
        "_tool": attr.label(default = "//rr/private:bazel_tool", executable = True, cfg = "exec"),
    },
)

def rr_evidence(name, tests, timeout = 300, local = False, testonly = True, **kwargs):
    """Runs `tests` inside a build action and collects their JUnit.

    See the rule documentation above; `testonly` defaults to True because the
    inputs are test targets.

    Args:
      name: target name.
      tests: test targets to run.
      timeout: per-test timeout in seconds.
      local: never execute remotely.
      testonly: Bazel testonly flag.
      **kwargs: common attributes.
    """
    _rr_evidence(name = name, tests = tests, timeout = timeout, local = local, testonly = testonly, **kwargs)

_FORMATS = ["html", "json", "md"]

def _rr_report_impl(ctx):
    outs = []
    args = ctx.actions.args()
    args.add("report")
    args.add_all("--model", ctx.files.model)
    evidence = []
    for e in ctx.attr.evidence:
        evidence.extend(e[DefaultInfo].files.to_list())
    args.add("--evidence")
    args.add_all(evidence, expand_directories = False)
    for fmt in _FORMATS:
        out = getattr(ctx.outputs, fmt + "_out")
        if out:
            outs.append(out)
            args.add("--" + fmt, out.path)
    if ctx.attr.title:
        args.add("--title", ctx.attr.title)
    if ctx.attr.strict:
        args.add("--strict")
    for k, v in ctx.attr.current_build.items():
        args.add("--current-build", "%s=%s" % (k, v))

    # The model's lock (rr_model(lock = ...)): the sets are pinned by it.
    locks = [m[RrModelInfo].lock for m in ctx.attr.model if RrModelInfo in m and m[RrModelInfo].lock]
    if len(locks) > 1:
        fail("%s: more than one model names a lock: %s" % (ctx.label, [f.short_path for f in locks]))
    if locks:
        args.add("--sets-lock", locks[0])
    if ctx.attr.lane:
        args.add("--lane", ctx.attr.lane)
    if ctx.file.lane_targets:
        args.add("--lane-targets", ctx.file.lane_targets)
    args.add("--on-attribution-error", ctx.attr.on_attribution_error)
    if ctx.files.srcs:
        # Implementation links: scan these sources for @rr(...) annotations.
        args.add_all(["--scan", "--root", ".", "--files"])
        args.add_all(ctx.files.srcs)
    ctx.actions.run(
        executable = ctx.executable._rr,
        arguments = [args],
        inputs = ctx.files.model + evidence + ctx.files.srcs + locks + ctx.files.lane_targets,
        outputs = outs,
        mnemonic = "RrReport",
        progress_message = "Building traceability report %{label}",
    )
    return [
        DefaultInfo(files = depset(outs)),
        RrReportInfo(
            json = ctx.outputs.json_out,
            lane = ctx.attr.lane,
            on_attribution_error = ctx.attr.on_attribution_error,
            lock = locks[0] if locks else None,
        ),
    ]

_rr_report = rule(
    implementation = _rr_report_impl,
    attrs = {
        "model": attr.label_list(mandatory = True, allow_files = [".yaml", ".yml", ".json"]),
        "evidence": attr.label_list(allow_files = True),
        "title": attr.string(),
        "strict": attr.bool(),
        "current_build": attr.string_dict(),
        "lane": attr.string(),
        "lane_targets": attr.label(allow_single_file = True),
        "on_attribution_error": attr.string(default = "fail", values = ["fail", "warn"]),
        "srcs": attr.label_list(allow_files = True),
        "html_out": attr.output(),
        "json_out": attr.output(),
        "md_out": attr.output(),
        "_rr": attr.label(default = "//python:rr", executable = True, cfg = "exec"),
    },
)

def rr_report(
        name,
        model,
        evidence = [],
        srcs = [],
        formats = _FORMATS,
        title = "",
        strict = False,
        current_build = {},
        check = False,
        lane = "",
        lane_targets = None,
        on_attribution_error = "fail",
        testonly = True,
        **kwargs):
    """Renders the traceability report for a model and its evidence.

    Outputs `<name>.html`, `<name>.json` and/or `<name>.md` (addressable as
    `:<name>.json` etc.). The JSON form is deterministic and suitable for
    `rr_golden_test`. The build fails when the model is invalid, when a test
    case is quarantined (unless `on_attribution_error = "warn"`), and when an
    attribution issue is an error (with `strict`, also every warning).

    Args:
      name: target name; also the output file stem.
      model: `rr_model` target(s) or model files. An `rr_model` with a `lock`
        pins the verification sets with it.
      evidence: `rr_evidence` targets and/or JUnit / records files.
      srcs: source files to scan for `@rr(...)` annotations; the report then
        links each requirement to the code that implements and verifies it.
      formats: any of "html", "json", "md".
      title: report title (default: the project name).
      strict: fail on model and attribution warnings too (`rr report --strict`).
      current_build: current artifact identity; evidence recorded against a
        different one is stale.
      check: also create `<name>_check_test`, which runs `rr check-report` on
        `<name>.json` (needs "json" in `formats`).
      lane: the lane the evidence comes from (`rr report --lane`).
      lane_targets: a file listing the targets that lane runs, one label per
        line (`--lane-targets`); not-run members of other targets read "out of
        lane".
      on_attribution_error: "fail" (a quarantined test case fails the build)
        or "warn" (the report is built; the case still counts for nobody).
      testonly: Bazel testonly flag (default True: evidence comes from tests).
      **kwargs: common attributes (visibility, tags, ...).
    """
    outs = {}
    for fmt in formats:
        if fmt not in _FORMATS:
            fail("unknown report format %r (expected one of %s)" % (fmt, _FORMATS))
        outs[fmt + "_out"] = "%s.%s" % (name, fmt)
    if check and "json" not in formats:
        fail("rr_report(check = True) needs \"json\" in formats: rr check-report reads the JSON report")
    _rr_report(
        name = name,
        model = model,
        evidence = evidence,
        title = title,
        strict = strict,
        current_build = current_build,
        lane = lane,
        lane_targets = lane_targets,
        on_attribution_error = on_attribution_error,
        srcs = srcs,
        testonly = testonly,
        **dict(kwargs, **outs)
    )
