"""Rule implementations behind //rr:defs.bzl."""

RrModelInfo = provider(
    doc = "Requirements model files.",
    fields = {"srcs": "depset of model files"},
)

RrEvidenceInfo = provider(
    doc = "Test evidence produced by rr_evidence.",
    fields = {"testlogs": "tree artifact laid out like bazel-testlogs"},
)

def _rr_model_impl(ctx):
    files = depset(ctx.files.srcs)
    return [
        DefaultInfo(files = files, runfiles = ctx.runfiles(files = ctx.files.srcs)),
        RrModelInfo(srcs = files),
    ]

rr_model_rule = rule(
    implementation = _rr_model_impl,
    doc = "Groups requirements model files (see rr_model).",
    attrs = {
        "srcs": attr.label_list(allow_files = [".yaml", ".yml", ".json"], mandatory = True),
    },
)

def _rr_main_impl(ctx):
    args = []
    for a in ctx.attr.baked_args:
        expanded = ctx.expand_location(a, ctx.attr.data)
        if "$(rootpaths " in a or "$(locations " in a:
            args.extend([p for p in expanded.split(" ") if p])
        else:
            args.append(expanded)
    ctx.actions.write(
        output = ctx.outputs.out,
        content = """# Generated by rules_requirements (rr_main); do not edit.
import sys

from rules_requirements.bazel import run_generated_main

if __name__ == "__main__":
    sys.exit(run_generated_main({entry}, {args}))
""".format(entry = json.encode(ctx.attr.entry), args = json.encode(args)),
    )

rr_main = rule(
    implementation = _rr_main_impl,
    doc = "Writes a Python main with its arguments baked in (see run_generated_main).",
    attrs = {
        "entry": attr.string(mandatory = True, values = ["cli", "pytest", "wrap", "bazel"]),
        "baked_args": attr.string_list(),
        "data": attr.label_list(allow_files = True),
        "out": attr.output(mandatory = True),
    },
)

def _workspace_of(label):
    return label.workspace_name or "_main"

def _rr_evidence_impl(ctx):
    out = ctx.actions.declare_directory(ctx.label.name + "/testlogs")
    args = ctx.actions.args()
    args.add("run-tests")
    args.add("--out", out.path)
    args.add("--timeout", str(ctx.attr.timeout))
    tools = []
    for t in ctx.attr.tests:
        ftr = t[DefaultInfo].files_to_run
        if not ftr or not ftr.executable:
            fail("%s is not executable" % t.label)
        tools.append(ftr)
        args.add("--test", "%s=%s=%s" % (t.label, ftr.executable.path, _workspace_of(t.label)))
    ctx.actions.run(
        executable = ctx.executable._tool,
        arguments = [args],
        outputs = [out],
        tools = tools,
        mnemonic = "RrEvidence",
        progress_message = "Running %d test(s) for evidence %%{label}" % len(ctx.attr.tests),
        execution_requirements = {"no-remote-exec": "1"} if ctx.attr.local else {},
    )
    return [
        DefaultInfo(files = depset([out])),
        RrEvidenceInfo(testlogs = out),
    ]

_rr_evidence = rule(
    implementation = _rr_evidence_impl,
    doc = """Runs tests inside a build action and collects their JUnit.

The output is a directory laid out like `bazel-testlogs`, so `rr_report` maps
each file back to its test label. Failing tests do not fail the build — they
are evidence, and the report shows them as FAILED. Use this for hermetic,
cacheable reports (and golden tests of them); for suites that cannot run in a
sandbox (hardware-in-the-loop), aggregate real `bazel-testlogs` with the `rr`
CLI instead.""",
    attrs = {
        "tests": attr.label_list(cfg = "exec", mandatory = True, doc = "Test targets to run."),
        "timeout": attr.int(default = 300, doc = "Per-test timeout in seconds."),
        "local": attr.bool(default = False, doc = "Never execute remotely."),
        "_tool": attr.label(default = "//rr/private:bazel_tool", executable = True, cfg = "exec"),
    },
)

def rr_evidence(name, tests, timeout = 300, local = False, testonly = True, **kwargs):
    """Runs `tests` inside a build action and collects their JUnit.

    See the rule documentation above; `testonly` defaults to True because the
    inputs are test targets.

    Args:
      name: target name.
      tests: test targets to run.
      timeout: per-test timeout in seconds.
      local: never execute remotely.
      testonly: Bazel testonly flag.
      **kwargs: common attributes.
    """
    _rr_evidence(name = name, tests = tests, timeout = timeout, local = local, testonly = testonly, **kwargs)

_FORMATS = ["html", "json", "md"]

def _rr_report_impl(ctx):
    outs = []
    args = ctx.actions.args()
    args.add("report")
    args.add_all("--model", ctx.files.model)
    evidence = []
    for e in ctx.attr.evidence:
        evidence.extend(e[DefaultInfo].files.to_list())
    args.add("--evidence")
    args.add_all(evidence, expand_directories = False)
    for fmt in _FORMATS:
        out = getattr(ctx.outputs, fmt + "_out")
        if out:
            outs.append(out)
            args.add("--" + fmt, out.path)
    if ctx.attr.title:
        args.add("--title", ctx.attr.title)
    if ctx.attr.strict:
        args.add("--strict")
    for k, v in ctx.attr.current_build.items():
        args.add("--current-build", "%s=%s" % (k, v))
    ctx.actions.run(
        executable = ctx.executable._rr,
        arguments = [args],
        inputs = ctx.files.model + evidence,
        outputs = outs,
        mnemonic = "RrReport",
        progress_message = "Building traceability report %{label}",
    )
    return [DefaultInfo(files = depset(outs))]

_rr_report = rule(
    implementation = _rr_report_impl,
    attrs = {
        "model": attr.label_list(mandatory = True, allow_files = [".yaml", ".yml", ".json"]),
        "evidence": attr.label_list(allow_files = True),
        "title": attr.string(),
        "strict": attr.bool(),
        "current_build": attr.string_dict(),
        "html_out": attr.output(),
        "json_out": attr.output(),
        "md_out": attr.output(),
        "_rr": attr.label(default = "//python:rr", executable = True, cfg = "exec"),
    },
)

def rr_report(name, model, evidence = [], formats = _FORMATS, title = "", strict = False, current_build = {}, testonly = True, **kwargs):
    """Renders the traceability report for a model and its evidence.

    Outputs `<name>.html`, `<name>.json` and/or `<name>.md` (addressable as
    `:<name>.json` etc.). The JSON form is deterministic and suitable for
    `rr_golden_test`.

    Args:
      name: target name; also the output file stem.
      model: `rr_model` target(s) or model files.
      evidence: `rr_evidence` targets and/or JUnit / records files.
      formats: any of "html", "json", "md".
      title: report title (default: the project name).
      strict: fail on model warnings too.
      current_build: current artifact identity; evidence recorded against a
        different one is stale.
      testonly: Bazel testonly flag (default True: evidence comes from tests).
      **kwargs: common attributes (visibility, tags, ...).
    """
    outs = {}
    for fmt in formats:
        if fmt not in _FORMATS:
            fail("unknown report format %r (expected one of %s)" % (fmt, _FORMATS))
        outs[fmt + "_out"] = "%s.%s" % (name, fmt)
    _rr_report(
        name = name,
        model = model,
        evidence = evidence,
        title = title,
        strict = strict,
        current_build = current_build,
        testonly = testonly,
        **dict(kwargs, **outs)
    )
